### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by pyure** [elytra/BetterBoilers#1]
- The version of the mod you are using (e.g. 2.0.0a4)
**1.0**
- Your Minecraft version (e.g. 1.11.2)
**1.12.2**
- Your Forge version (e.g. 13.20.0.2252)
**14.23.0.2549**
- The crash report or log, uploaded to gist.github.com
**N/A**

I strongly suspect I'm getting ahead of you a bit here, so apologies for that.  Just in case however: as a mod for pack developers, obviously we'll need configurability.

Some suggested properties:
* Steam per cycle/fuel/whatever (CRITICAL)
* auto-steam output percentage (Railcraft boilers automatically output steam when at 50% capacity)
* Maximum block count
* Minimum block count ( I suspect these might not be simple to add depending on how you check the multiblock)

Critically, anything that impacts the fuel balance, in order to facilitate integration into a pack that has other mods in it.  ( By way of comparison, its not unusual for a unit of coal to produce 30,000 steam in various mods.  See Railcraft, Gregtech, etc.)

Again, I'll be shocked to my core if you aren't already halfway through this before you read it.  Thanks for the mod, team.

**Comment by LemmaEOF** [comment]
Oh right, I forgot to add a minimum block count! I'm definitely going to work on adding config soon. Configurability is a big thing that's important for me, so it's my next priority.
Min/max block count would be very easy to add, so it's not a big deal. I'll get working on this as soon as I can.

**Comment by LemmaEOF** [comment]
Okay, I've now added config! You can change:
- amount of ticks for one boil
- how much steam is gotten out of one boil
- the maximum number of blocks allowed in a boiler multiblock
- the minimum number of blocks allowed in a boiler multiblock (no boilers have a min yet though)

Auto-output is gonna come in a future update, because it's not as complex as it'd seem from a player perspective.

**Comment by pyure** [comment]
Exceptional.  Great start to a useful utility mod guys.
