### ISSUE TITLE
Items get voided inside Boiler Hatch / Boiler Controller during re-forming

### ISSUE THREAD

**Issue by Vyraal1** [elytra/BetterBoilers#10]
- Better Boilers 1.1.31
- Minecraft 1.12.2
- Forge 2594

**How to Replicate**
Make any type of boiler structure, put fuel in it and then break the structure in any way (eg. put a firebox casing on a level same as Boiler Components, or break all boiler components connected to the firebox levels). The structure will unform, deleting all of the items inside of the boiler controller (it doesn't even spit it out). Reforming the structure correctly does not return the items.

**Comment by LemmaEOF** [comment]
And it doesn't void the water or steam in it? Hm. I'll need to see what I did to fix it for water and steam for this sort of issue.

**Comment by LemmaEOF** [comment]
Oh, found what might be the problem. Let me try this out.

**Comment by LemmaEOF** [comment]
Due to another issue at the moment with controllers, I can't test this out. I'll need to leave it open for now.

**Comment by LemmaEOF** [comment]
Hmm, it looks like something with inventory serialization and blockstate changes. I'll check up on what the workaround is.
