### ISSUE TITLE
Issues with blocks

### ISSUE THREAD

**Issue by calloatti** [elytra/BetterBoilers#13]
- The version of the mod you are using BetterBoilers-1.1.1
- Your Minecraft version 1.12.2
- Your Forge version 14.23.1.2594

1.Please make blocks harder to break. One hit with a diamond pick breaks 3/4 blocks

2.Blocks vanish when not broken with a pick. One hit with your hand and a couple of blocks vanish.

**Comment by LemmaEOF** [comment]
Oh boy, I never set hardness, did I.

**Comment by calloatti** [comment]
Nope

**Comment by LemmaEOF** [comment]
I'll see if it's possible for me sometime to put that in a 1.1.2 but it'd take a lot of undoing stuff in the current dev.

**Comment by calloatti** [comment]
Don't worry, just take your time. It's not gamebreaking.

**Comment by calloatti** [comment]
By the way I love that I have a use now for all that coal. Thanks!
