### ISSUE TITLE
Multiblock size counting incorrect

### ISSUE THREAD

**Issue by LemmaEOF** [elytra/BetterBoilers#16]
Quote from CurseForge:
>I am using the 1.2-dev.55 beta, and it seems that a 10 x 10 x 5 boiler (500 blocks) is the maximum size, as a 10 x 10 x 6 (600 blocks) gives an error stating that the maximum size is 1000 blocks, which is larger than the boiler I built. If the maximum size has changed, could the error be updated? Otherwise, could that (likely) math error be fixed?

**Comment by LemmaEOF** [comment]
It looks like the maximum possible blocks in a boiler at the moment is 576, a 10x10x5 with 76 blocks on top. It's definitely [this function](https://github.com/elytra/BetterBoilers/blob/master/src/main/java/com/elytradev/betterboilers/tile/TileEntityMultiblockController.java%23L39) that has the problem since that's where the boiler size check is.

**Comment by exaskye** [comment]
As your scan code is adapted from Correlated, you also adopt the Correlated network scanner's main pitfall: it includes "misses" in the iteration count. So if you have a single block with no other valid blocks next to it, `itr` will be 7. This pitfall is detailed [in the last paragraph of the scanning section of the Controller wiki page](https://github.com/elytra/Correlated/wiki/Controller#network-scanning).

**Comment by LemmaEOF** [comment]
Oh yay. It all boils down to having to rebuild the scan code again. I've really gotta try and do something with that sometime.

**Comment by exaskye** [comment]
You can monkey patch this in the interim by checking `members.size()` instead of `itr`, as you're using it for gameplay balance rather than a performance optimization.

**Comment by LemmaEOF** [comment]
Yeah, I'll do that for now. Still gotta fix the scanning as a whole, but that'll fix it for now.

**Comment by LiaungYip** [comment]
Note to others: This bug was fixed in https://github.com/elytra/BetterBoilers/commit/9458cf3d81d69c1f12a1c1e09f6465e7ef9fce5b however still exists in the latest version on CurseForge [(v1.2-dev.55)](https://www.curseforge.com/minecraft/mc-mods/better-boilers/files/2538026) which was released before patch https://github.com/elytra/BetterBoilers/commit/9458cf3d81d69c1f12a1c1e09f6465e7ef9fce5b.

A workaround is to change the config in `betterboilers.cfg`, from `I:defaultMaxMultiblock=1000` to a very large number, say `I:defaultMaxMultiblock=999999`.

**Comment by LemmaEOF** [comment]
oh god right I never published this bugfix, did I? I'll do that sometime soon.

**Comment by LiaungYip** [comment]
@Boundarybreaker Ha! Given https://github.com/elytra/BetterBoilers/issues/17#issuecomment-618598577 I wasn't expecting any maintenance. :)

**Comment by LemmaEOF** [comment]
Well luckily I don't actually need to write a single line of code to get this published, since it's already fixed ^^;

**Comment by LemmaEOF** [comment]
The fix for this is [now live](https://www.curseforge.com/minecraft/mc-mods/better-boilers/files/2947886).

**Comment by LiaungYip** [comment]
Thanks @Boundarybreaker !
