### ISSUE TITLE
Revive the project

### ISSUE THREAD

**Issue by LemmaEOF** [elytra/BetterBoilers#17]
RailCraft just got notable for unsavory practices again, so I think I wanna finally get around to actually finishing BB. Here's what we gotta do:

1. There's still a lot of issues with the scanning code; it only checks every few seconds and has been known to accidentally double-count some blocks. This got mitigated a little with #16, but I wanna make sure it's well and truly put to rest.
2. Whenever a boiler is reconstructed, it can potentially lose its current inventory and tank contents. This is also very not good, so it needs to be looked into.
3. The turbine is mostly done, but it needs proper textures and recipes. I need to decide on what the turbine will be made out of, then get @InsomniaKitten to make the textures.
4. The documentation is currently not the best. Optimally I wanna be able to use something like Patchouli or Charset Tablet. 
5. My proxy blocks are still a little finnicky with visual connection stuff (#14),  and I wanna see what's going on there. I might need to take a look at other mods for sample code.

**Comment by LemADEC** [comment]
Sharing my thoughts on those:
1. Scanning every few seconds is fine. No need to lag the server checking thousands of blocks that most of the time won't change.
2. In term of lore, I think it would make more sense to reset the boiler steam/water when its setup change (say, if scan returns different result).

**Comment by LemmaEOF** [comment]
number 1 is a good point, but I do feel like something *absolutely* needs to be done about number 2. It's causing people to lose any fuel in the machine, which is just bad game design.

**Comment by LemADEC** [comment]
1. I understand the scanning is still a bit wonky, so that part still could use some love.
2. I was completing your proposal, as it wasn't specific on just fuel or things like water and steam. 
I've tried today and didn't notice a lost of fuel, so I guess it's intermittent?

**Comment by Mattzi** [comment]
@Boundarybreaker will it be revived?

**Comment by LemmaEOF** [comment]
Probably not; I got *very* burnt out on the Forge environment.

**Comment by LemmaEOF** [comment]
The project has now been put up for adoption, as I won't be continuing to work on it any time in the foreseeable future. I'll update here if someone decides to pick it up, but for now it's pretty much dead.
