### ISSUE TITLE
Steam Pump only outputs steam via IE pipes via a pump. 

### ISSUE THREAD

**Issue by DrUltraLux** [elytra/BetterBoilers#20]
Only way I have found to get steam out of the tank is via an Immersive Engineering Pump and pipes. 
Doesn't seem to work for anything else in any other other modpack.

Tested on over a dozen mods so far.

**Comment by LemmaEOF** [comment]
I used Extra Utilities fluid transfer modes during development/testing for the mod. It might be something weird with the valve/vent capabilities.

**Comment by DrUltraLux** [comment]
I'll try it out with the mod you used for now then. 
I'd like to identify the issue and resolve that asap.

**Comment by DrUltraLux** [comment]
Tested, works great,  though pipes dont visually attach. 

It seems that IE and EU are the only mods this works with though, so that explains people having trouble.

**Comment by DrUltraLux** [comment]
![image](https://user-images.githubusercontent.com/63906224/83124548-b15ae580-a119-11ea-85bb-231a62b624af.png)

**Comment by DrUltraLux** [comment]
![image](https://user-images.githubusercontent.com/63906224/83138684-816a0d00-a12e-11ea-83ac-b8ede30014dc.png)

Simple Wooden Pipes also works!

**Comment by DrUltraLux** [comment]
Found the issue. The blocks that pipes are to connect to need to extend a different object type. I'll fix that once I can make commits.

**Comment by LemmaEOF** [comment]
Sent an invite to the repo.
