### ISSUE TITLE
How to build Boiler?

### ISSUE THREAD

**Issue by SihenZhang** [elytra/BetterBoilers#3]
Minecraft Version: 1.12.2
Forge Version: 14.23.1.2586
Mod Version: 1.1
Singleplayer/Multiplayer: Singleplayer

Additional Information:
* I copy the boiler form from CurseForge Images, but it doesn't work.
![](https://i.imgur.com/7QDXBAC.png)
![](https://i.imgur.com/wFb6KYl.png)
* So could you tell me where I can find a guide about how to build boiler?

**Comment by LemmaEOF** [comment]
The default-size boiler like that needs to be solid, too. There isn't any specific restriction to its form. The only requirements are:
- there must be at least 36 total blocks.
- all firebox blocks must be on the bottom level.
- all boiler blocks must be above the bottom level.

**Comment by SihenZhang** [comment]
Well, it's solid. 

And I think I found a bug. That's why it will happen. I will submit a new issue.

**Comment by SihenZhang** [comment]
Well, when I put the 37th block, it works. 
However, when it is 36 blocks, it doesn't work.
Is this a bug?

**Comment by LemmaEOF** [comment]
Ah, I see what went wrong. I forgot to actually make the method counting the number of blocks in the multiblock include the controller. Fixed, releasing version 1.1.1 with fix.
