### ISSUE TITLE
Change lang file key

### ISSUE THREAD

**Issue by exzhawk** [elytra/BetterBoilers#5]
Forge 2555, Better Boilers master-1.1.29, Storage Drawers 1.12.1-5.3.3
![rr e2d b60bvmk412c 1ku](https://user-images.githubusercontent.com/7038938/34904125-076f0406-f87a-11e7-952f-b9ae9adc6c45.png)
https://github.com/elytra/BetterBoilers/blob/master/src/main/resources/assets/betterboilers/lang/en_US.lang#L12
https://github.com/jaquadro/StorageDrawers/blob/1.12/resources/assets/storagedrawers/lang/en_us.lang#L75
You are using the same key.
Hmmmmm...
https://github.com/search?utf8=%E2%9C%93&q=%22tile.controller.name%22+extension%3Alang&type=Code&ref=advsearch&l=&l=

**Comment by LemmaEOF** [comment]
…oh, right. I forgot that lang files aren't namespaced. Fixed, gonna release version 1.1.1 in just a bit incorporating fixes for this and #3
